name: Update Sponsors README

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaÃ±a Actions
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automÃ¡ticamente cada dÃ­a a medianoche

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # Necesario para hacer push del README actualizado
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      # - name: Generate Sponsors â€“ Cluster ($50) ğŸ¢
      #   uses: JamesIves/github-sponsors-readme-action@v1
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     file: 'README.md'
      #     marker: 'cluster'
      #     minimum: 5000
      #     fallback: ''

      - name: Generate Sponsors â€“ Book Patron ($10) ğŸ–‹ï¸
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          file: 'README.md'
          marker: 'book'
          minimum: 1000
          maximum: 4999
          fallback: ''

      - name: Generate Sponsors â€“ Container ($3) ğŸ³
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          file: 'README.md'
          marker: 'container'
          minimum: 300
          maximum: 999
          fallback: ''

      - name: Commit and push README ğŸ“¤
        run: |
          git config user.name "${{ secrets.GIT_USER_NAME || github.actor }}"
          git config user.email "${{ secrets.GIT_USER_EMAIL || format('{0}@users.noreply.github.com', github.actor) }}"
          git diff --quiet README.md || {
            git add README.md
            git commit -m "ğŸ’– Update sponsors in README"
            git push
          }
