name: Update Sponsors README

on:
  workflow_dispatch: # Permite ejecutarlo manualmente desde la pestaÃ±a Actions
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automÃ¡ticamente cada dÃ­a a medianoche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Generate Sponsors ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          file: 'README.md'
          # ConfiguraciÃ³n visual (puedes ajustar esto luego)
          markers: 'true'
          minimum: 100 # Opcional: Si quisieras mostrar solo a los que pagan mÃ­nimo X centavos
          columns: 6   # NÃºmero de avatares por fila
          width: 80    # TamaÃ±o del avatar en px
